In [3]:
import numpy as np

In [4]:
l = [1,2,3,4]

In [5]:
arr = np.array(l)

In [6]:
type(arr)

numpy.ndarray

In [7]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [8]:
np.asarray(l)

array([1, 2, 3, 4])

In [9]:
a = [2,3,4]

In [10]:
np.asanyarray(a)

array([2, 3, 4])

In [11]:
b = np.matrix(l)  # matrix 2 Dimensional hai

In [12]:
b

matrix([[1, 2, 3, 4]])

In [13]:
np.asanyarray(b)  # l not convert in array

matrix([[1, 2, 3, 4]])

In [14]:
a = np.array(l)

In [15]:
c = a # shallow copy

In [16]:
c

array([1, 2, 3, 4])

In [17]:
c[0] = 100

In [18]:
c

array([100,   2,   3,   4])

In [19]:
a

array([100,   2,   3,   4])

In [20]:
d = np.copy(a) #deep copy

In [21]:
d

array([100,   2,   3,   4])

In [22]:
a

array([100,   2,   3,   4])

In [23]:
a [1] = 400

In [24]:
a

array([100, 400,   3,   4])

In [25]:
d

array([100,   2,   3,   4])

In [26]:
np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [27]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [28]:
iterable = (i*i for i in range(5))

In [29]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [30]:
np.fromstring("234 343", sep= ' ')

array([234., 343.])

In [31]:
np.fromstring("2,3", sep= ',')

array([2., 3.])

numpy -> data types


In [33]:
l = [1,2,3,4,5]

In [34]:
arr = np.array(l)

In [35]:
arr

array([1, 2, 3, 4, 5])

In [36]:
arr.ndim

1

In [37]:
arr2 = np.array([[1,2,3,4], [5,7,8,9]])

In [38]:
arr2

array([[1, 2, 3, 4],
       [5, 7, 8, 9]])

In [39]:
arr2.ndim

2

In [40]:
arr.size

5

In [41]:
arr

array([1, 2, 3, 4, 5])

In [42]:
arr2

array([[1, 2, 3, 4],
       [5, 7, 8, 9]])

In [43]:
arr.shape

(5,)

In [44]:
arr2.shape

(2, 4)

In [45]:
arr.dtype

dtype('int32')

In [46]:
arr2.dtype

dtype('int32')

In [47]:
arr22 = np.array([(1.3,45,45), (45,34,56)])

In [48]:
arr22

array([[ 1.3, 45. , 45. ],
       [45. , 34. , 56. ]])

In [49]:
arr22.dtype

dtype('float64')

In [50]:
list(range(5))

[0, 1, 2, 3, 4]

In [51]:
list(range(01,5))

SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (2313710390.py, line 1)

In [52]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [53]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [54]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [55]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [56]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [57]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [58]:
arr3 = np.zeros((3,4,2,3))

In [59]:
arr3.ndim

4

In [60]:
arr3

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [61]:
np.ones(4)

array([1., 1., 1., 1.])

In [62]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [63]:
on = np.ones((2,3,2))

In [64]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [65]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [66]:
on * 4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [67]:
np.empty((3,5))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 6.81019663e-310]])

In [68]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [69]:
np.linspace(2,4, 20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [70]:
np.logspace(2,5,10, base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [71]:
arr = np.random.randn(3,4)

In [72]:
import pandas as pd

In [73]:
pd.DataFrame(arr)

0         1         2         3
0 -0.850808 -0.288782  0.943687  1.528746
1 -2.338646 -0.334898 -0.090249  0.343723
2 -1.879048 -0.797507 -0.680651  1.031022

In [74]:
np.random.rand(3,4)

array([[0.08919363, 0.47631009, 0.1689415 , 0.4850847 ],
       [0.64417769, 0.91973632, 0.24644423, 0.70519504],
       [0.03818314, 0.15803081, 0.66042662, 0.72043582]])

In [75]:
pd.DataFrame(np.random.randint(1,110, (300,400))).to_csv('test.csv')

In [76]:
arr = np.random.rand(3,4)

In [77]:
arr

array([[0.49813819, 0.92371342, 0.60248105, 0.73688155],
       [0.17946778, 0.05121356, 0.098232  , 0.94541156],
       [0.32420482, 0.33774346, 0.11693711, 0.62364086]])

In [78]:
arr.reshape(6,2)

array([[0.49813819, 0.92371342],
       [0.60248105, 0.73688155],
       [0.17946778, 0.05121356],
       [0.098232  , 0.94541156],
       [0.32420482, 0.33774346],
       [0.11693711, 0.62364086]])

In [79]:
arr1 = arr.reshape(6,-1)

In [80]:
arr1[1][1]

0.7368815549011593

In [81]:
arr1[2:5,1]

array([0.05121356, 0.94541156, 0.33774346])

In [84]:
arr = np.random.randint(1,100, (5,5))

In [85]:
arr

array([[18, 83, 68,  1, 69],
       [35, 84, 73, 86, 64],
       [21, 61, 96,  8, 93],
       [93, 38, 33, 42,  5],
       [29, 11, 74, 92,  3]])

In [87]:
arr[arr > 50]

array([83, 68, 69, 84, 73, 86, 64, 61, 96, 93, 93, 74, 92])

In [88]:
arr

array([[18, 83, 68,  1, 69],
       [35, 84, 73, 86, 64],
       [21, 61, 96,  8, 93],
       [93, 38, 33, 42,  5],
       [29, 11, 74, 92,  3]])

In [89]:
arr[2:4,[1,2]]

array([[61, 96],
       [38, 33]])

In [92]:
arr[0][0] = 5000

In [93]:
arr

array([[5000,   83,   68,    1,   69],
       [  35,   84,   73,   86,   64],
       [  21,   61,   96,    8,   93],
       [  93,   38,   33,   42,    5],
       [  29,   11,   74,   92,    3]])

In [181]:
# inbuild function


In [95]:
arr1 = np.random.randint(1,3, (3,3))
arr2 = np.random.randint(1,3, (3,3))

In [96]:
arr1

array([[2, 1, 2],
       [1, 1, 1],
       [2, 2, 2]])

In [97]:
arr2

array([[2, 2, 1],
       [2, 2, 2],
       [2, 1, 2]])

In [98]:
arr1+arr2

array([[4, 3, 3],
       [3, 3, 3],
       [4, 3, 4]])

In [99]:
arr1-arr2

array([[ 0, -1,  1],
       [-1, -1, -1],
       [ 0,  1,  0]])

In [100]:
arr1/arr2

array([[1. , 0.5, 2. ],
       [0.5, 0.5, 0.5],
       [1. , 2. , 1. ]])

In [101]:
arr1 * arr2

array([[4, 2, 2],
       [2, 2, 2],
       [4, 2, 4]])

In [102]:
arr1

array([[2, 1, 2],
       [1, 1, 1],
       [2, 2, 2]])

In [104]:
# matrix multiplication

arr1@arr2

array([[10,  8,  8],
       [ 6,  5,  5],
       [12, 10, 10]])

In [105]:
arr1/0

C:\Users\Mohd Wasil\AppData\Local\Temp\ipykernel_13692\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [106]:
arr1 + 100

array([[102, 101, 102],
       [101, 101, 101],
       [102, 102, 102]])

In [107]:
arr1 **2

array([[4, 1, 4],
       [1, 1, 1],
       [4, 4, 4]])

In [108]:
# Numpy -> Broadcasting

In [110]:
arr = np.zeros((4,4))

In [111]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [112]:
row = np.array([1,2,3,4])

In [113]:
row # linear array

array([1, 2, 3, 4])

In [115]:
arr  + row  # row bis broadcasting

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [116]:
# columns bis

In [117]:
row.shape

(4,)

In [118]:
row.T

array([1, 2, 3, 4])

In [120]:
col = np.array([[1,2,3,4]])

In [121]:
 col.T

array([[1],
       [2],
       [3],
       [4]])

In [122]:
col

array([[1, 2, 3, 4]])

In [123]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [124]:
col

array([[1, 2, 3, 4]])

In [125]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [126]:
arr1 = np.random.randint(1,4, (3,4))

In [127]:
arr1

array([[1, 2, 3, 3],
       [1, 2, 2, 3],
       [1, 1, 2, 1]])

In [128]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081, 1.73205081],
       [1.        , 1.41421356, 1.41421356, 1.73205081],
       [1.        , 1.        , 1.41421356, 1.        ]])

In [129]:
np.exp(arr1)

array([[ 2.71828183,  7.3890561 , 20.08553692, 20.08553692],
       [ 2.71828183,  7.3890561 ,  7.3890561 , 20.08553692],
       [ 2.71828183,  2.71828183,  7.3890561 ,  2.71828183]])

In [130]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125, 0.47712125],
       [0.        , 0.30103   , 0.30103   , 0.47712125],
       [0.        , 0.        , 0.30103   , 0.        ]])

PART -> 02

In [131]:
import numpy as np

In [132]:
# numpy -> array Manipulation

In [133]:
arr = np.random.randint(1,10, (3,4))

In [134]:
arr

array([[7, 7, 3, 9],
       [3, 1, 1, 2],
       [3, 7, 4, 7]])

In [135]:
arr.reshape(6,2)

array([[7, 7],
       [3, 9],
       [3, 1],
       [1, 2],
       [3, 7],
       [4, 7]])

In [136]:
arr.reshape(2,6)

array([[7, 7, 3, 9, 3, 1],
       [1, 2, 3, 7, 4, 7]])

In [137]:
arr.reshape(2,7)

ValueError: cannot reshape array of size 12 into shape (2,7)

In [138]:
arr.reshape(2,-2336)

array([[7, 7, 3, 9, 3, 1],
       [1, 2, 3, 7, 4, 7]])

In [139]:
arr.T # array rotate

array([[7, 3, 3],
       [7, 1, 7],
       [3, 1, 4],
       [9, 2, 7]])

In [140]:
arr

array([[7, 7, 3, 9],
       [3, 1, 1, 2],
       [3, 7, 4, 7]])

In [141]:
arr.flatten() # 2 dimension convert one dimension

array([7, 7, 3, 9, 3, 1, 1, 2, 3, 7, 4, 7])

In [142]:
arr1 = np.array([1,2,3,3,4])

In [143]:
arr1.ndim

1

In [144]:
np.expand_dims(arr1, axis=1)  # 1 convert 2D

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [145]:
np.expand_dims(arr1, axis=0)

array([[1, 2, 3, 3, 4]])

In [146]:
arr

array([[7, 7, 3, 9],
       [3, 1, 1, 2],
       [3, 7, 4, 7]])

In [147]:
np.squeeze(arr)

array([[7, 7, 3, 9],
       [3, 1, 1, 2],
       [3, 7, 4, 7]])

In [148]:
data = np.array([[1], [2], [3]])

In [149]:
data

array([[1],
       [2],
       [3]])

In [150]:
np.squeeze(data)

array([1, 2, 3])

In [151]:
arr1

array([1, 2, 3, 3, 4])

In [152]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [153]:
np.roll(arr1, 2)

array([3, 4, 1, 2, 3])

In [154]:
arr1

array([1, 2, 3, 3, 4])

In [156]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [157]:
# Numpy -> Binary Operations

In [158]:
arr1 = np.random.randint(1,10, (3,4))

In [159]:
arr2 = np.random.randint(1,10, (3,4))

In [160]:
arr1

array([[4, 9, 3, 1],
       [3, 3, 4, 1],
       [1, 1, 4, 5]])

In [161]:
arr2

array([[1, 7, 9, 1],
       [6, 3, 1, 3],
       [5, 6, 3, 2]])

In [162]:
arr1+arr2

array([[ 5, 16, 12,  2],
       [ 9,  6,  5,  4],
       [ 6,  7,  7,  7]])

In [163]:
arr1*arr2

array([[ 4, 63, 27,  1],
       [18,  9,  4,  3],
       [ 5,  6, 12, 10]])

In [164]:
arr1/arr2

array([[4.        , 1.28571429, 0.33333333, 1.        ],
       [0.5       , 1.        , 4.        , 0.33333333],
       [0.2       , 0.16666667, 1.33333333, 2.5       ]])

In [165]:
arr1-arr2

array([[ 3,  2, -6,  0],
       [-3,  0,  3, -2],
       [-4, -5,  1,  3]])

In [166]:
# remainder operation
arr1%arr2

array([[0, 2, 3, 0],
       [3, 0, 0, 1],
       [1, 1, 1, 1]])

In [167]:
arr1 ** arr2

array([[      4, 4782969,   19683,       1],
       [    729,      27,       4,       1],
       [      1,       1,      64,      25]])

In [168]:
arr1 & arr2

array([[0, 1, 1, 1],
       [2, 3, 0, 1],
       [1, 0, 0, 0]])

In [169]:
arr1

array([[4, 9, 3, 1],
       [3, 3, 4, 1],
       [1, 1, 4, 5]])

In [170]:
arr2

array([[1, 7, 9, 1],
       [6, 3, 1, 3],
       [5, 6, 3, 2]])

In [171]:
-arr1

array([[-4, -9, -3, -1],
       [-3, -3, -4, -1],
       [-1, -1, -4, -5]])

In [172]:
arr1|arr2

array([[ 5, 15, 11,  1],
       [ 7,  3,  5,  3],
       [ 5,  7,  7,  7]])

In [173]:
arr1>arr2

array([[ True,  True, False, False],
       [False, False,  True, False],
       [False, False,  True,  True]])

In [174]:
#Numpy -> String Function

In [175]:
arr = np.array(['wasil','sudh'])

In [176]:
arr

array(['wasil', 'sudh'], dtype='<U5')

In [177]:
np.char.upper(arr)

array(['WASIL', 'SUDH'], dtype='<U5')

In [178]:
np.char.title(arr)

array(['Wasil', 'Sudh'], dtype='<U5')

In [179]:
np.char.capitalize(arr)

array(['Wasil', 'Sudh'], dtype='<U5')

In [180]:
#Numpy -> Mathematic function

In [182]:
arr1

array([[4, 9, 3, 1],
       [3, 3, 4, 1],
       [1, 1, 4, 5]])

In [183]:
np.sin(arr1)

array([[-0.7568025 ,  0.41211849,  0.14112001,  0.84147098],
       [ 0.14112001,  0.14112001, -0.7568025 ,  0.84147098],
       [ 0.84147098,  0.84147098, -0.7568025 , -0.95892427]])

In [184]:
np.cos(arr1)

array([[-0.65364362, -0.91113026, -0.9899925 ,  0.54030231],
       [-0.9899925 , -0.9899925 , -0.65364362,  0.54030231],
       [ 0.54030231,  0.54030231, -0.65364362,  0.28366219]])

In [185]:
np.tan(arr1)

array([[ 1.15782128, -0.45231566, -0.14254654,  1.55740772],
       [-0.14254654, -0.14254654,  1.15782128,  1.55740772],
       [ 1.55740772,  1.55740772,  1.15782128, -3.38051501]])

In [186]:
np.tanh(arr1)

array([[0.9993293 , 0.99999997, 0.99505475, 0.76159416],
       [0.99505475, 0.99505475, 0.9993293 , 0.76159416],
       [0.76159416, 0.76159416, 0.9993293 , 0.9999092 ]])

In [187]:
np.log10(arr1)

array([[0.60205999, 0.95424251, 0.47712125, 0.        ],
       [0.47712125, 0.47712125, 0.60205999, 0.        ],
       [0.        , 0.        , 0.60205999, 0.69897   ]])

In [188]:
np.exp(arr1)

array([[5.45981500e+01, 8.10308393e+03, 2.00855369e+01, 2.71828183e+00],
       [2.00855369e+01, 2.00855369e+01, 5.45981500e+01, 2.71828183e+00],
       [2.71828183e+00, 2.71828183e+00, 5.45981500e+01, 1.48413159e+02]])

In [189]:
np.sqrt(arr1)

array([[2.        , 3.        , 1.73205081, 1.        ],
       [1.73205081, 1.73205081, 2.        , 1.        ],
       [1.        , 1.        , 2.        , 2.23606798]])

In [191]:
np.power(arr1,2)

array([[16, 81,  9,  1],
       [ 9,  9, 16,  1],
       [ 1,  1, 16, 25]], dtype=int32)

In [192]:
np.mean(arr1)

3.25

In [193]:
np.median(arr1)

3.0

In [194]:
np.std(arr1)

2.203217344400381

In [195]:
np.var(arr1)

4.854166666666667

In [196]:
np.min(arr1)

1

In [197]:
np.max(arr1)

9

In [198]:
arr1

array([[4, 9, 3, 1],
       [3, 3, 4, 1],
       [1, 1, 4, 5]])

In [199]:
# Sort, Search, Counting function

In [200]:
import numpy as np

In [201]:
arr = np.array([4,5,3,4,6,5,7,8,977,69,9,6,6,3,333,44,22])

In [202]:
arr

array([  4,   5,   3,   4,   6,   5,   7,   8, 977,  69,   9,   6,   6,
         3, 333,  44,  22])

In [203]:
np.sort(arr)

array([  3,   3,   4,   4,   5,   5,   6,   6,   6,   7,   8,   9,  22,
        44,  69, 333, 977])

In [204]:
np.searchsorted(arr, 34)

8

In [205]:
arr1 = np.array([0,343,323,56,0,0,0,0])

In [207]:
np.count_nonzero(arr1)

3

In [208]:
arr

array([  4,   5,   3,   4,   6,   5,   7,   8, 977,  69,   9,   6,   6,
         3, 333,  44,  22])

In [209]:
np.where(arr > 6)

(array([ 6,  7,  8,  9, 10, 14, 15, 16], dtype=int64),)

In [210]:
np.extract(arr > 6, arr)

array([  7,   8, 977,  69,   9, 333,  44,  22])

In [211]:
# Numpy -> Byte Swapping

In [212]:
arr

array([  4,   5,   3,   4,   6,   5,   7,   8, 977,  69,   9,   6,   6,
         3, 333,  44,  22])

In [213]:
arr.byteswap()

array([  67108864,   83886080,   50331648,   67108864,  100663296,
         83886080,  117440512,  134217728, -788332544, 1157627904,
        150994944,  100663296,  100663296,   50331648, 1291911168,
        738197504,  369098752])

In [214]:
# Numpy -> Copies & Views

In [215]:
arr

array([  4,   5,   3,   4,   6,   5,   7,   8, 977,  69,   9,   6,   6,
         3, 333,  44,  22])

In [216]:
a = np.copy(arr) # Deep copy

In [217]:
a

array([  4,   5,   3,   4,   6,   5,   7,   8, 977,  69,   9,   6,   6,
         3, 333,  44,  22])

In [225]:
b = arr.view() # shallow Copy

In [226]:
b 

array([ 67,   5,   3,   4,   6,   5,   7,   8, 977,  69,   9,   6,   6,
         3, 333,  44,  22])

In [220]:
b[0] = 67

In [221]:
b

array([ 67,   5,   3,   4,   6,   5,   7,   8, 977,  69,   9,   6,   6,
         3, 333,  44,  22])

In [222]:
arr

array([ 67,   5,   3,   4,   6,   5,   7,   8, 977,  69,   9,   6,   6,
         3, 333,  44,  22])

In [227]:
# Numpy -> Matrix library

In [228]:
import numpy.matlib as nm

In [229]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [230]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [231]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [232]:
# Numpy -> Linear Algebra

In [233]:
arr1 = np.random.randint([[2,3], [4,5]])

In [234]:
arr2 = np.random.randint([[5,3], [2,5]])

In [235]:
np.dot(arr1,arr2)

array([[0, 4],
       [0, 8]])

In [236]:
arr1@arr2

array([[0, 4],
       [0, 8]])